export const foodData = [
  { food: "Chocolate", safeAmount: "None, toxic" },
  { food: "Grapes", safeAmount: "None, toxic" },
  { food: "Raisins", safeAmount: "None, toxic" },
  { food: "Onions", safeAmount: "None, toxic" },
  { food: "Garlic", safeAmount: "None, toxic" },
  { food: "Avocado", safeAmount: "None, toxic" },
  { food: "Alcohol", safeAmount: "None, toxic" },
  { food: "Caffeine", safeAmount: "None, toxic" },
  { food: "Xylitol", safeAmount: "None, toxic" },
  { food: "Macadamia nuts", safeAmount: "None, toxic" },
  { food: "Nutmeg", safeAmount: "None, toxic" },
  { food: "Alcohol-based foods or sauces", safeAmount: "None, toxic" },
  { food: "Bones (especially cooked)", safeAmount: "None, toxic" },
  { food: "Corn on the cob", safeAmount: "None, toxic" },
  { food: "Moldy or spoiled food", safeAmount: "None, toxic" },
  {
    food: "Human medications (unless prescribed by a veterinarian)",
    safeAmount: "None, toxic",
  },
  { food: "Ibuprofen (Advil)", safeAmount: "None, toxic" },
  { food: "Acetaminophen (Tylenol)", safeAmount: "None, toxic" },
  { food: "Antifreeze (ethylene glycol)", safeAmount: "None, toxic" },
  { food: "Rat poison", safeAmount: "None, toxic" },
  { food: "Insecticides", safeAmount: "None, toxic" },
  { food: "Household cleaning products", safeAmount: "None, toxic" },
  { food: "Tobacco and nicotine products", safeAmount: "None, toxic" },
  { food: "Raw yeast dough", safeAmount: "None, toxic" },
  {
    food: "Fruit pits and seeds (e.g., cherry pits, apple seeds)",
    safeAmount: "None, toxic",
  },
  { food: "Fatty foods (can cause pancreatitis)", safeAmount: "None, toxic" },
  { food: "High-salt foods", safeAmount: "None, toxic" },
  { food: "Dairy products (lactose intolerance)", safeAmount: "None, toxic" },
  { food: "Raw eggs (risk of salmonella)", safeAmount: "None, toxic" },
  {
    food: "Cooked bones (can splinter and cause blockages)",
    safeAmount: "None, toxic",
  },
  { food: "Hops (used in brewing)", safeAmount: "None, toxic" },
  { food: "Almonds", safeAmount: "None, toxic" },
  { food: "Coffee grounds", safeAmount: "None, toxic" },
  { food: "Tea (caffeine content)", safeAmount: "None, toxic" },
  { food: "Persimmons", safeAmount: "None, toxic" },
  { food: "Peach and plum pits", safeAmount: "None, toxic" },
  { food: "Raw seafood (risk of parasites)", safeAmount: "None, toxic" },
  { food: "Mushrooms (some varieties are toxic)", safeAmount: "None, toxic" },
  { food: "Human vitamins and supplements", safeAmount: "None, toxic" },
  { food: "Corn cobs (can cause blockages)", safeAmount: "None, toxic" },
  { food: "Rhubarb leaves", safeAmount: "None, toxic" },
  { food: "Spoiled or moldy food", safeAmount: "None, toxic" },
  { food: "Moldy nuts or grains", safeAmount: "None, toxic" },
  { food: "Fertilizers", safeAmount: "None, toxic" },
  { food: "Herbicides", safeAmount: "None, toxic" },
  { food: "Pesticides", safeAmount: "None, toxic" },
  {
    food: "Certain human foods high in fat (can lead to pancreatitis)",
    safeAmount: "None, toxic",
  },
  {
    food: "Tofu (large amounts of soy can be harmful)",
    safeAmount: "None, toxic",
  },
  {
    food: "Yeast-based dough (can expand in the stomach)",
    safeAmount: "None, toxic",
  },
  { food: "Marijuana (THC can be toxic to dogs)", safeAmount: "None, toxic" },
  { food: "Apples", safeAmount: "Small quantities, remove seeds and core" },
  { food: "Blueberries", safeAmount: "Small quantities" },
  { food: "Strawberries", safeAmount: "Small quantities" },
  { food: "Bananas", safeAmount: "Small quantities" },
  {
    food: "Watermelon",
    safeAmount: "Small quantities, seedless and without rind",
  },
  {
    food: "Cantaloupe",
    safeAmount: "Small quantities, seedless and without rind",
  },
  { food: "Cucumbers", safeAmount: "Small quantities, sliced" },
  { food: "Carrots", safeAmount: "Small quantities, sliced or diced" },
  { food: "Green beans", safeAmount: "Small quantities" },
  { food: "Peas", safeAmount: "Small quantities" },
  { food: "Spinach", safeAmount: "Small quantities, cooked" },
  { food: "Kale", safeAmount: "Small quantities, cooked" },
  { food: "Broccoli", safeAmount: "Small quantities, steamed or cooked" },
  { food: "Cauliflower", safeAmount: "Small quantities, steamed or cooked" },
  { food: "Zucchini", safeAmount: "Small quantities, cooked" },
  { food: "Pumpkin", safeAmount: "Small quantities, cooked" },
  { food: "Sweet potatoes", safeAmount: "Small quantities, cooked" },
  { food: "Rice", safeAmount: "Small quantities, cooked, plain" },
  { food: "Oatmeal", safeAmount: "Small quantities, cooked, plain" },
  { food: "Quinoa", safeAmount: "Small quantities, cooked, plain" },
  { food: "Plain, cooked chicken", safeAmount: "Small quantities, no bones" },
  { food: "Plain, cooked turkey", safeAmount: "Small quantities, no bones" },
  {
    food: "Lean ground beef",
    safeAmount: "Small quantities, cooked, no seasoning",
  },
  { food: "Salmon", safeAmount: "Small quantities, cooked, no bones" },
  { food: "Tuna", safeAmount: "Small quantities, cooked, no bones" },
  { food: "Eggs", safeAmount: "Small quantities, cooked, no seasoning" },
  { food: "Cottage cheese", safeAmount: "Small amounts" },
  {
    food: "Plain yogurt",
    safeAmount: "Small amounts, no artificial sweeteners",
  },
  { food: "Peanut butter", safeAmount: "In moderation, without xylitol" },
  { food: "Cheese", safeAmount: "Small amounts" },
  { food: "Fish oil", safeAmount: "As a supplement" },
  { food: "Flaxseeds", safeAmount: "Ground, as a supplement" },
  { food: "Coconut oil", safeAmount: "As a supplement" },
  { food: "Cinnamon", safeAmount: "A small pinch, avoid powder" },
  { food: "Honey", safeAmount: "A small amount" },
  { food: "Brown rice cakes", safeAmount: "Small amounts, plain" },
  { food: "Whole wheat bread", safeAmount: "Small amounts" },
  { food: "Sliced almonds", safeAmount: "A few pieces, unsalted" },
  { food: "Cashews", safeAmount: "A few pieces, unsalted" },
  { food: "Sunflower seeds", safeAmount: "A few pieces, unsalted" },
  { food: "Pumpkin seeds", safeAmount: "A few pieces, unsalted" },
  { food: "Chia seeds", safeAmount: "Soaked" },
  { food: "Pears", safeAmount: "Small quantities, remove seeds and core" },
  { food: "Peaches", safeAmount: "Small quantities, remove pits" },
  { food: "Plums", safeAmount: "Small quantities, remove pits" },
  { food: "Mango", safeAmount: "Small quantities, remove pit and skin" },
  { food: "Papaya", safeAmount: "Small quantities, remove seeds and skin" },
  { food: "Celery", safeAmount: "Small quantities, sliced or diced" },
  { food: "Bell peppers", safeAmount: "Small quantities, sliced" },
  { food: "Asparagus", safeAmount: "Small quantities, steamed or cooked" },
  {
    food: "Plain, cooked chicken (no bones)",
    safeAmount: "Safe in any amount",
  },
  { food: "Plain, cooked turkey (no bones)", safeAmount: "Safe in any amount" },
  { food: "Plain, cooked beef (no bones)", safeAmount: "Safe in any amount" },
  { food: "Plain, cooked pork (no bones)", safeAmount: "Safe in any amount" },
  { food: "Plain, cooked fish (no bones)", safeAmount: "Safe in any amount" },
  {
    food: "Plain, cooked eggs (no seasoning)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked tofu (small amounts)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked rice (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked pasta (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked oatmeal (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked quinoa (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked sweet potatoes (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked pumpkin (plain, in moderation)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked carrots (sliced or diced)",
    safeAmount: "Safe in any amount",
  },
  { food: "Plain, cooked green beans", safeAmount: "Safe in any amount" },
  { food: "Plain, cooked peas", safeAmount: "Safe in any amount" },
  {
    food: "Plain, cooked broccoli (steamed or cooked)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked cauliflower (steamed or cooked)",
    safeAmount: "Safe in any amount",
  },
  { food: "Plain, cooked zucchini (cooked)", safeAmount: "Safe in any amount" },
  {
    food: "Plain, cooked spinach (small amounts, cooked)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked kale (small amounts, cooked)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain, cooked asparagus (small amounts, steamed or cooked)",
    safeAmount: "Safe in any amount",
  },
  { food: "Blueberries", safeAmount: "Safe in any amount" },
  { food: "Strawberries", safeAmount: "Safe in any amount" },
  { food: "Bananas", safeAmount: "Safe in any amount" },
  { food: "Apples (remove seeds and core)", safeAmount: "Safe in any amount" },
  {
    food: "Watermelon (seedless and without rind)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Cantaloupe (seedless and without rind)",
    safeAmount: "Safe in any amount",
  },
  { food: "Cucumbers (sliced)", safeAmount: "Safe in any amount" },
  { food: "Bell peppers (sliced)", safeAmount: "Safe in any amount" },
  { food: "Celery (sliced or diced)", safeAmount: "Safe in any amount" },
  { food: "Sliced almonds (unsalted)", safeAmount: "Safe in any amount" },
  { food: "Cashews (unsalted)", safeAmount: "Safe in any amount" },
  { food: "Sunflower seeds (unsalted)", safeAmount: "Safe in any amount" },
  { food: "Pumpkin seeds (unsalted)", safeAmount: "Safe in any amount" },
  { food: "Chia seeds (soaked)", safeAmount: "Safe in any amount" },
  { food: "Coconut oil (as a supplement)", safeAmount: "Safe in any amount" },
  { food: "Fish oil (as a supplement)", safeAmount: "Safe in any amount" },
  {
    food: "Flaxseeds (ground, as a supplement)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Plain yogurt (small amounts, no artificial sweeteners)",
    safeAmount: "Safe in any amount",
  },
  { food: "Cottage cheese (small amounts)", safeAmount: "Safe in any amount" },
  {
    food: "Peanut butter (in moderation, without xylitol)",
    safeAmount: "Safe in any amount",
  },
  { food: "Cheese (small amounts)", safeAmount: "Safe in any amount" },
  { food: "Honey (in moderation)", safeAmount: "Safe in any amount" },
  { food: "Brown rice cakes (plain)", safeAmount: "Safe in any amount" },
  {
    food: "Whole wheat bread (small amounts)",
    safeAmount: "Safe in any amount",
  },
  {
    food: "Cinnamon (a small pinch, avoid powder)",
    safeAmount: "Safe in any amount",
  },
  { food: "Olive oil (as a supplement)", safeAmount: "Safe in any amount" },
  { food: "Turmeric (as a supplement)", safeAmount: "Safe in any amount" },
  {
    food: "Nutritional yeast (as a supplement)",
    safeAmount: "Safe in any amount",
  },
];
